<?php
/**
*  Shippit Pty Ltd
*
*  NOTICE OF LICENSE
*
*  This source file is subject to the terms
*  that is available through the world-wide-web at this URL:
*  http://www.shippit.com/terms
*
*  @category   Shippit
*  @copyright  Copyright (c) Shippit Pty Ltd (http://www.shippit.com)
*  @author     Matthew Muscat <matthew@mamis.com.au>
*  @license    http://www.shippit.com/terms
*/
?>
<?php $_shipment = $this->getShipment() ?>
<?php $_order = $this->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border: 1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Shipped By') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size: 13px; padding: 3px 9px"><?php echo $this->__('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $i = 0 ?>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <?php
            $i++;
            $_trackingNumberDetail = $_item->getNumberDetail();

            if ($_trackingNumberDetail && $_trackingNumberDetail instanceof Mage_Shipping_Model_Tracking_Result_Status) {
                $_trackingUrl = $_trackingNumberDetail->getUrl();
            }
            else {
                $_trackingUrl = false;
            }
        ?>
        <tr <?php echo $i%2?'bgcolor="#F6F6F6"':'' ?>>
            <td align="left" valign="top" style="padding: 3px 9px"><?php echo $this->escapeHtml($_item->getTitle()) ?></td>
            <td align="center" valign="top" style="padding: 3px 9px">
                <?php if ($_trackingUrl): ?>
                    <a href="<?php echo $_trackingUrl ?>"><?php echo $this->escapeHtml($_item->getNumber()) ?></a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($_item->getNumber()) ?>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
