<?php
/**
 * Shippit Pty Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the terms
 * that is available through the world-wide-web at this URL:
 * http://www.shippit.com/terms
 *
 * @category   Shippit
 * @copyright  Copyright (c) Shippit Pty Ltd (http://www.shippit.com)
 * @author     Matthew Muscat <matthew@mamis.com.au>
 * @license    http://www.shippit.com/terms
 */
?>
<table cellspacing="0" class="form-list" style="margin-top: 10px;">
    <tr>
        <td class="label">
            <label>Authority to Leave</label>
        </td>
        <td class="value">
            <strong><?php echo $this->escapeHtml($this->getShippitAuthorityToLeave()) ?></strong>
        </td>
    </tr>
    <tr>
        <td class="label">
            <label>Delivery Instructions</label>
        </td>
        <td class="value">
            <strong><?php echo $this->escapeHtml($this->getShippitDeliveryInstructions()) ?></strong>
        </td>
    </tr>
</table>
