<?php
/**
*  Shippit Pty Ltd
*
*  NOTICE OF LICENSE
*
*  This source file is subject to the terms
*  that is available through the world-wide-web at this URL:
*  http://www.shippit.com/terms
*
*  @category   Shippit
*  @copyright  Copyright (c) Shippit Pty Ltd (http://www.shippit.com)
*  @author     Matthew Muscat <matthew@mamis.com.au>
*  @license    http://www.shippit.com/terms
*/
?>

<div id="onepage-checkout-shipping-method-shippit-authoritytoleave">
    <ul class="form-list">
        <li class="control">
            <!-- Shippit Authority To Leave Checkbox -->
            <input name="<?php echo $this->getFieldId() ?>" type="checkbox" title="<?php echo $this->getLabelText() ?>" class="checkbox" id="<?php echo $this->getFieldId() ?>" <?php echo ($this->getValue() ? 'checked' : '') ?> />
            <label for="<?php echo $this->getFieldId() ?>">
                <?php echo $this->getLabelText() ?>
            </label>
        </li>
    </ul>
</div>
