<?php
/**
*  Shippit Pty Ltd
*
*  NOTICE OF LICENSE
*
*  This source file is subject to the terms
*  that is available through the world-wide-web at this URL:
*  http://www.shippit.com/terms
*
*  @category   Shippit
*  @copyright  Copyright (c) Shippit Pty Ltd (http://www.shippit.com)
*  @author     Matthew Muscat <matthew@mamis.com.au>
*  @license    http://www.shippit.com/terms
*/
?>

<div id="onepage-checkout-shipping-method-shippit-deliveryinstructions">
    <ul class="form-list">
        <li class="wide">
            <!-- Shippit Delivery Instructions Textarea -->
            <label for="<?php echo $this->getFieldId(); ?>">
                <?php echo $this->getLabelText() ?>
            </label>
            <div class="input-box">
                <textarea id="<?php echo $this->getFieldId() ?>" name="<?php echo $this->getFieldId() ?>" style="min-height: 145px;"><?php echo $this->getValue() ?></textarea>
            </div>
        </li>
    </ul>
</div>
